/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rzm_ffmpeglibrary_FFmpegUtils */

#ifndef _Included_com_rzm_ffmpeglibrary_FFmpegUtils
#define _Included_com_rzm_ffmpeglibrary_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rzm_ffmpeglibrary_FFmpegUtils
 * Method:    decode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_rzm_ffmpeglibrary_FFmpegUtils_decode
  (JNIEnv *, jclass,jstring,jstring);

#ifdef __cplusplus
}
#endif
#endif
