/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_app_rzm_utils_Encryptils */

#ifndef _Included_com_app_rzm_utils_EncryptUtils
#define _Included_com_app_rzm_utils_EncryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app_rzm_utils_Encryptils
 * Method:    encryptToMd5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_app_rzm_utils_EncryptUtils_encryptToMd5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
